# Generated by Django 5.2.15 on 2026-08-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='user', max_length=20)),
                ('realName', models.CharField(blank=True, max_length=50, null=True)),
                ('departmentName', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('expireTime', models.DateTimeField(blank=True, null=True)),
                ('lastLoginTime', models.DateTimeField(blank=True, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'sysUser',
            },
        ),
        migrations.CreateModel(
            name='ApsArchive',
            fields=[
                ('archiveId', models.BigAutoField(primary_key=True, serialize=False)),
                ('archiveName', models.CharField(max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.SmallIntegerField(default=0)),
                ('createdBy', models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.PROTECT, related_name='apsArchives', to='core.sysuser')),
            ],
            options={
                'db_table': 'apsArchive',
            },
        ),
        migrations.CreateModel(
            name='TaskImportRecord',
            fields=[
                ('taskId', models.BigAutoField(primary_key=True, serialize=False)),
                ('sourceType', models.SmallIntegerField(default=1)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('importStatus', models.SmallIntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.SmallIntegerField(default=0)),
                ('apsArchive', models.ForeignKey(db_column='apsArchiveId', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.apsarchive')),
                ('createdBy', models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.sysuser')),
                ('sourceTask', models.ForeignKey(blank=True, db_column='sourceTaskId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskimportrecord')),
            ],
            options={
                'db_table': 'taskImportRecord',
            },
        ),
        migrations.CreateModel(
            name='SolveTask',
            fields=[
                ('solveTaskId', models.BigAutoField(primary_key=True, serialize=False)),
                ('inputParams', models.JSONField()),
                ('solveStatus', models.SmallIntegerField(default=0)),
                ('finishReason', models.SmallIntegerField(blank=True, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('finishTime', models.DateTimeField(blank=True, null=True)),
                ('resultFilePath', models.CharField(blank=True, max_length=255, null=True)),
                ('partialResultFilePath', models.CharField(blank=True, max_length=255, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.SmallIntegerField(default=0)),
                ('createdUser', models.ForeignKey(db_column='createdUserId', on_delete=django.db.models.deletion.PROTECT, related_name='solveTasks', to='core.sysuser')),
                ('task', models.ForeignKey(db_column='taskId', on_delete=django.db.models.deletion.PROTECT, related_name='solveTasks', to='core.taskimportrecord')),
            ],
            options={
                'db_table': 'solveTask',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('fileId', models.BigAutoField(primary_key=True, serialize=False)),
                ('originalName', models.CharField(max_length=255)),
                ('fileName', models.CharField(max_length=255)),
                ('filePath', models.CharField(max_length=255)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('parseStatus', models.SmallIntegerField(default=0)),
                ('parseMessage', models.CharField(blank=True, max_length=1000, null=True)),
                ('isDeleted', models.SmallIntegerField(default=0)),
                ('uploadUser', models.ForeignKey(db_column='uploadUserId', on_delete=django.db.models.deletion.PROTECT, related_name='uploadFiles', to='core.sysuser')),
            ],
            options={
                'db_table': 'uploadFile',
            },
        ),
        migrations.AddField(
            model_name='taskimportrecord',
            name='file',
            field=models.ForeignKey(db_column='fileId', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.uploadfile'),
        ),
        migrations.CreateModel(
            name='UploadFileItem',
            fields=[
                ('itemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
                ('materialCode', models.CharField(max_length=50)),
                ('inventoryName', models.CharField(max_length=255)),
                ('specification', models.CharField(max_length=255)),
                ('u8CurrentStock', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('monthlyProductionPlan', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('submittedTotal', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.SmallIntegerField(default=0)),
                ('file', models.ForeignKey(db_column='fileId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.uploadfile')),
            ],
            options={
                'db_table': 'uploadFileItem',
            },
        ),
        migrations.CreateModel(
            name='ApsArchiveItem',
            fields=[
                ('itemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('packageSpecification', models.CharField(max_length=255)),
                ('mixingLine', models.CharField(blank=True, max_length=100, null=True)),
                ('mixingBatchQuantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('mixingShiftOutput', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('mixingWorkerCount', models.IntegerField(blank=True, null=True)),
                ('tabletPress', models.CharField(blank=True, max_length=100, null=True)),
                ('tabletingShiftOutput', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tabletingWorkerCount', models.IntegerField(blank=True, null=True)),
                ('coatingMachine', models.CharField(blank=True, max_length=100, null=True)),
                ('coatingShiftOutput', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('coatingWorkerCount', models.IntegerField(blank=True, null=True)),
                ('dividingEquipment', models.CharField(blank=True, max_length=100, null=True)),
                ('dividingShiftOutput', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('dividingWorkerCount', models.IntegerField(blank=True, null=True)),
                ('packagingEquipment', models.CharField(blank=True, max_length=100, null=True)),
                ('packagingShiftOutput', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('manualPackagingOutput', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('packagingWorkerCount', models.IntegerField(blank=True, null=True)),
                ('productionCycleDays', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('centralizedProcurement', models.SmallIntegerField(blank=True, null=True)),
                ('annualSales', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.SmallIntegerField(default=0)),
                ('archive', models.ForeignKey(db_column='archiveId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.apsarchive')),
            ],
            options={
                'db_table': 'apsArchiveItem',
                'indexes': [models.Index(fields=['archive', 'isDeleted'], name='apsArchiveI_archive_37fffb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apsarchive',
            index=models.Index(fields=['createdBy', 'isDeleted'], name='apsArchive_created_501a46_idx'),
        ),
        migrations.AddIndex(
            model_name='solvetask',
            index=models.Index(fields=['createdUser', 'solveStatus'], name='solveTask_created_992a83_idx'),
        ),
        migrations.AddIndex(
            model_name='taskimportrecord',
            index=models.Index(fields=['createdBy', 'isDeleted', 'createTime'], name='taskImportR_created_b9d2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadfileitem',
            index=models.Index(fields=['file', 'materialCode'], name='uploadFileI_fileId_e0bf54_idx'),
        ),
    ]
