# Generated by Django 5.2.15 on 2026-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='loginToken',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
